name: Build YTMusicUltimate
on:
  workflow_dispatch:
    inputs:
      display_name:
        description: "App Name (Optional)"
        default: "YouTube Music"
        required: true
        type: string
      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtubemusic"
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build YTMusicUltimate
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          path: main
          submodules: recursive
      - name: Install Dependencies
        run: brew install make ldid
      - name: Set PATH environment variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV
      - name: Cache Theos
        id: theos
        uses: actions/cache@v4
        env:
          cache-name: theos_cache_344ee59
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}
      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: 344ee5925df036dbd1312b783ad5a00d153c2445
          path: theos
          submodules: recursive
      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
      - name: Build Tweak for Sideloading
        run: |
          cd main
          make clean package DEBUG=0 FINALPACKAGE=1 SIDELOADING=1
          mv packages/*.deb ../ytmult.deb
      - name: Inject tweak into rootless IPA
        run: cyan -i main/ytm.ipa -o YTMusicUltimate.ipa -uwsf ytmult.deb -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}
      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YTMusicUltimate-${{ github.run_number }}
          path: YTMusicUltimate.ipa
          retention-days: 30
